# Generated by Django 5.1.3 on 2024-12-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enclave', '0003_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='photos/profile_pics/IMG-20220507-WA0012.jpg', null=True, upload_to='photos/profile_pics/'),
        ),
    ]
