# Generated by Django 5.1.3 on 2024-12-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enclave', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='photos/profile_pics/IMG-20220507-WA0012.jpg', null=True, upload_to='Photos/profile_pics/'),
        ),
    ]
