# Generated by Django 5.1.3 on 2024-11-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['roll', 'email'], name='student_stu_roll_6ea252_idx'),
        ),
    ]
